version: 2.1

orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.1

jobs:
  tests:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm run lint
      - run: npm run test:coverage
      - codecov/upload:
          file: coverage/*.json

workflows:
  ci:
    jobs:
      - tests
