version: 2.1

orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.1

jobs:
  tests:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm run lint
      - run: npm run cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - run:
          name: Package version check
          command: node scripts/check-version GuilhermeBeneti1990 React_Project_2021

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
